services:
  - type: web
    name: fate-deck-oracle
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false  # Set this in Render dashboard
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
    buildCommand: echo "Using Dockerfile for build"
    startCommand: ./bin/rails server
    healthCheckPath: /up
    autoDeploy: true
